name: Node.js CI

on:
  push:
    branches: ['**']
  schedule:
    - cron: '0 18 1 * *' # 1st of every month
  workflow_dispatch: # Enables running workflow manually

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      # - name: Auto-lint app
      #   shell: bash        
      #   run: |
      #     ./.github/workflows/code-lint.sh
      - run: npm run health-check
      - run: npm run integration
      - run: git submodule update --init --recursive
      - run: docker build .
