name: Node.js CI

on:
  push:
    branches: ['**']
  schedule:
    - cron: '0 18 * * FRI' # Every Friday at 6pm
  workflow_dispatch: # Enables running workflow manually

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Auto-lint app
        run: |
          ./.github/workflows/code-lint.sh
        shell: bash      
      - run: npm run health-check
      - run: npm run integration
      - run: git submodule update --init --recursive
      - run: docker build .
