name: Node.js CI

on:
  push:
    branches: [ modpack/latest ]
  pull_request:
    branches: [ modpack/latest ]
  schedule:
    # Every Friday at 6pm
    - cron: "0 18 * * FRI"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run health-check
    - run: git submodule update --init --recursive
    - run: docker build .    